src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\CallbackValidator;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=CalendarRepository::class)
 */
class Calendar
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $PublishedAt;

    /**
     * @ORM\OneToMany(targetEntity=CategoryReference::class, mappedBy="calendar")
     * @ORM\OrderBy({"position"="ASC"})
     */
    private $categoryReferences;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    public function __construct()
    {
        $this->categoryReferences = new ArrayCollection();
    }
    
    public function getId()
    {
        return $this->id;
    }

    public function getPublishedAt(): ?bool
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(?bool $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;
        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->PublishedAt;
    }

    /**
     * @return Collection|CategoryReference[]
     */
    public function getCategoryReferences(): Collection
    {
        return $this->categoryReferences;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Calendar;
use App\Repository\CalendarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class HomeController extends AbstractController
{
    /**
     * @Route("/homepage", name="app_homepage")
     */
    public function homepage(EntityManagerInterface $em, CalendarRepository $calendarRepo)
    {
//        $repository = $em->getRepository(Calendar::class);
//        $calendars = $repository->findAll();
//        return $this->render('home/home_page.html.twig', [
//            'calendars' => $calendars,
//
//        ]);

        $calendars = $calendarRepo->findAll();
        return $this->render('home/home_page.html.twig', [
            'calendars' => $calendars,

        ]);
    }

    /**
     * @Route("homepage/calendar_show/{slug}", name="calendar_show")
     */
    public function show(Calendar $calendar, $slug,EntityManagerInterface $em)
    {
//        $repository = $em->getRepository(Calendar::class);
//        /** @var Calendar $calendar */
//        $calendar = $repository->findOneBy(['slug' => $slug]);
//        if (!$calendar) {
//            throw $this->createNotFoundException(sprintf('No calendar for slug "%s"', $slug));
//        }
//        dd($calendar);
        return $this->render('home/show.html.twig', [
//            'title' => ucwords(str_replace('-', ' ', $slug)),
            'calendar' => $calendar,
        ]);
    }
}

templates/home/home_page.html.twig
{% extends 'base.html.twig' %}

{% block title %} Learning Box Calendar {% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <!-- Article List -->
            <div class="col-sm-12">
                <!-- H1 Article -->
                <a class="main-article-link" href="#">
                    <div class="main-article mb-5 pb-3">
                        <img src="{{ asset('images/november.jpeg') }}" alt="meteor shower">
                        <h1 class="text-center mt-2">November</h1>
                    </div>
                </a>
                <!-- Supporting Calendar -->
                    {% for calendar in calendars %}
                        <div class="article-container my-1">
                        {% if calendar.publishedAt == true %}
                            <a href="{{ path('calendar_show', {slug: calendar.slug}) }}">
    {#                            <img class="article-img" src="{{ asset('images/asteroid.jpeg') }}">#}
                                <div class="col-md-3 article-title d-inline-block pl-3 align-middle">
                                    <span>{{ calendar.title }}</span>
                                    <br>
    {#                                <span class="pl-5 article-details float-right"> {{ calendar.publishedAt ? calendar.publishedAt }}</span>#}
                                </div>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}

        </div>
    </div>
{% endblock %}
{% block content_class %}{{ parent() }} show-article-container-border-green{% endblock %}

{% block content_body %}

{% endblock %}

templates/home/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{#    {% block title %}{{ title }}{% endblock %}#}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="show-article-container p-3 mt-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <h5>Day title:</h5>
                            <div class="show-article-title-container d-inline-block pl-3 align-middle">
                                <span class="show-article-title ">{{ calendar.title }}</span>
                                <br>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col-sm-12">
                                    <h5>Daily Notes</h5>
                                    <div class="article-text">
                                        {{ calendar.content}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <h3>Files</h3>
                            <ul class="list-group small">
                                <ul class="list-group small js-reference-list" data-url="{{ path('admin_calendar_list_references', {id: calendar.id}) }}"></ul>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {#    {{ encore_entry_link_tags('admin_article_form') }}#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css" integrity="sha256-e47xOkXs1JXFbjjpoRr1/LhVcqSzRmGmPqsrUQeVs+g=" crossorigin="anonymous" />
{% endblock %}


{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js" integrity="sha256-cs4thShDfjkqFGk5s2Lxj35sgSRr4MRcyccmi0WKqCM=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.8.3/Sortable.min.js" integrity="sha256-uNITVqEk9HNQeW6mAAm2PJwFX2gN45l8a4yocqsFI6I=" crossorigin="anonymous"></script>

    {{ encore_entry_script_tags('admin_article_form') }}

{% endblock %}